version: '3'

services:
  master:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h@angeSoftB1og
  slave1:
    image: "postgres"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h@angeSoftB1og
    depends_on:
      - master
  zookeeper:
    image: zookeeper:3.5.8
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zookeeper:2888:3888
#    depends_on:
#      - slave1
  kafka1:
    image: confluentinc/cp-kafka:6.0.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    depends_on:
      - master
  app:
    build: .
    ports:
      - "9000:9000"
#    environment:
#      SPRING_MASTER_DATASOURCE_URL: jdbc:postgresql://master/hello
#      SPRING_MASTER_DATASOURCE_USERNAME: postgres
#      SPRING_MASTER_DATASOURCE_PASSWORD: h@angeSoftB1og
#      SPRING_SLAVE_DATASOURCE_URL: jdbc:postgresql://slave1/hello
#      SPRING_SLAVE_DATASOURCE_USERNAME: postgres
#      SPRING_SLAVE_DATASOURCE_PASSWORD: h@angeSoftB1og
    depends_on:
      - redis

